### PR TITLE
Form for Access Control Allow Origin

### PR DESCRIPTION
**Pull request by deathart**
Hi everyone, to start off sorry about my English, I'm using a translator.

I have created a web interface with Angular, which is problematic (that's not bad at all) with the "Access Control Allow Origin" header.

That's why I created a small form to manage this option to avoid to put it hard in the code and that it is modifiable.

### CODE REVIEW

**Comment by Phyxion** [comment]
A setting for this would be fine but this is such a limited use case that I don't see a need to add this to UI.

**Comment by deathart** [comment]
For my part I needed a modifiable field because my dev and prod environment are totally different so I found it more practical. Otherwise if you have to modify it by hand I find it long and annoying.

Why not make a general form for the web server ? allowing to modify the port, the header "Access Control Allow Origin" and other parameters.

By the same occasion why are the requests to retrieve the sensors in POST and not in GET ?

**Comment by Phyxion** [comment]
I've not written that so the reason I don't know. I understand your use case but I don't think this is something you want to change frequently so adding a form for just this setting seems too much. I would accept the changes to HttpServer.cs and MainForm.cs (apart from the ServerAccessControl_Click method)

**Comment by deathart** [comment]
All right, if not why not make a general form for the web server ? allowing to modify the port, the header "Access Control Allow Origin" and other parameters.

By the same occasion why are the requests to retrieve the sensors in POST and not in GET ?

**Comment by lordmortis** [comment]
@deathart should we instead add Get methods for data retrieval? (which, i must admit, seems more REST-y?)

**Comment by deathart** [comment]
We all agree that the `GET' is more `REST API'.

**Comment by Phyxion** [comment]
If you add this option to the new authentication form (so the access control form can be removed) I can merge this. You'll need to rebase it on master.

**Comment by deathart** [comment]
The best way to close this PR is for me to recreate a new, cleaner one.

**Pull request closed without merging**
