### PR TITLE
Add embedded controller sensors for ROG STRIX X570-E GAMING

### PR DESCRIPTION
**Pull request by zeule**
Based on the information provided by @berniyh in [comment](https://github.com/electrified/asus-wmi-sensors/issues/62#issuecomment-617375332) and PR #453.

### CODE REVIEW

**Comment by PhyxionNL** [comment]
Is this ready to merge?

**Comment by zeule** [comment]
It would be nice to get a feedback from an owner of this motherboard. Maybe @berniyh can provide us with that? The built program can be downloaded from the CI run in this PR.

**Comment by berniyh** [comment]
Sorry yes, I forgot …

It's working fine and I think the sensor output is correct. :)

**Comment by zeule** [comment]
Thanks!

**Comment by Rem0o** [comment]
I'm getting a bunch of report of the following:

6/16/2021 8:45:36 AM: System.ApplicationException: Object synchronization method was called from an unsynchronized block of code.
at System.Threading.Mutex.ReleaseMutex()
at LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.WindowsEmbeddedControllerIO.Dispose(Boolean disposing)
at LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.WindowsEmbeddedControllerIO.Finalize()

Looking at the code, all WindowsEmbeddedControllerIO instance are in a "using" statement. How can the finalizer call the dispose in a case where the dispose wasn't called prior?

**Pull request merged**
