### PR TITLE
Graphics cards refactoring

### PR DESCRIPTION
**Pull request by matteofabbri**

### CODE REVIEW

**Comment by Phyxion** [comment]
I think we should undo the style changes again, it's very hard to read now. And it's sharing some of the same data as the other PR (which I still need to review) 👍

**Comment by matteofabbri** [comment]
Ok, no problem.
But you seriously find more readable ten class in the same file ?

**Comment by Phyxion** [comment]
No, separating the classes is fine, but all code inside the Gpu classes has also been formatted differently. That makes reviewing code changes very hard :)

**Comment by cybermerlin** [comment]
@Phyxion , bad idea closing PR if not like the style, just get this PR n change style to as u wish n merge it if will be ok after styling.
So, now, u just do not respect his work for your project - very bad.

**Comment by matteofabbri** [comment]
@cybermerlin don't worry i use a professional tool for this kind of refactorings, it's just a matter of couple of clicks.
@Phyxion i suggest you to use it too, it will simplify dramattically your job. 

https://www.jetbrains.com/resharper/

**Comment by Phyxion** [comment]
I already use ReSharper, I'm completely fine with refactoring (the code style simply isn't great), but all formatting changes make it almost unreadable on GitHub to check what has changed, that's all.

**Pull request closed without merging**
