### PR TITLE
Bugfix: AMD 39xx CCD Temperatures

### PR DESCRIPTION
**Pull request by sebastian-dev**

### CODE REVIEW

**Comment by Phyxion** [comment]
What does this fix exactly?

**Comment by sebastian-dev** [comment]
The CCDs not ordered continuous (0,1,2,3...). When the cpu has no CCD2, CCD3 is not read out.

**Comment by Phyxion** [comment]
> 
> 
> The CCDs not ordered continuous (0,1,2,3...). When the cpu has no CCD2, CCD3 is not read out.

OK, is this done now to merge?

**Comment by sebastian-dev** [comment]
It is done, but i cant can test it. I dont have a ryzen 3000 threadripper.

**Pull request merged**
