### PR TITLE
build externals from source

### PR DESCRIPTION
**Pull request by dwilhelm**
This is a recreation of PR #875 from OHM.

In general, it's better to make components from source instead of trusting DLLs tracked in the repo, especially when the External binaries are easy to make at compile time.

Future changes to External should be more straightforward this way.

### CODE REVIEW

**Comment by bigpodgurc** [comment]
Well easyer for end user who might not know as much about coding

**Comment by bigpodgurc** [comment]
Second thing is licences

**Comment by dwilhelm** [comment]
True, but as long as the source compiles successfully (which it should be doing anyway), with project references there are no extra steps required; it's still the same amount of work to make the solution.

**Comment by dwilhelm** [comment]
I'm not a lawyer, but I wouldn't expect license to be an issue. The source code for all External projects are already included in the repo. This commit just starts using it as part of the main project and solution.

**Comment by dwilhelm** [comment]
For the travis failure, I notice that it's looking for file name dvsplit.cur (all lower case), while `git ls-tree` has DVSplit.cur.

I don't know about the travis setup, but please let me know if I can help with other info.

**Comment by dwilhelm** [comment]
Fixed old paths in Resources.resx that didn't match case, so travis is now happy.

**Comment by bigpodgurc** [comment]
Is there any benefit for using the way your describing

**Comment by bigpodgurc** [comment]
So lets just clarify what exacly are you describing

**Comment by dwilhelm** [comment]
Sure, sounds good.

The short answer is that it's safer and easier to maintain for no extra cost.

The long answer:

The current setup is a little weird, since the OHM repo includes both the source code for third party projects and a compiled file for that source. I've only ever seen one or the other.

There are two benefits to using only source, and removing the DLLs. One benefit is trust and the other is maintainability.

For a user that wants to compile OHM from source because they don't want to trust an installer, the current setup with included DLLs is no safer than using the installer. Even though you're compiling the main OHM source, you still have to trust that Aga.Controls.dll and other third party libraries were made using the source advertised in the repo. The paranoid would rather use only source code.

Also, there's no extra cost for using source instead of DLLs, since the OHM repo already includes all necessary source code for third party projects under External. Other applications might require users go looking other source separately and make those as prerequisites, but the OHM repo has always included the third party source under External. So when the project/solution uses project references instead of committed DLLs, users can still clone this repo, open the solution Visual Studio, and the build will "just work".

For maintenance, it can be a problem to include both the source code for third party projects and a compiled DLL. It's too easy to accidentally (or maliciously) update the source code but not the DLL, or the other way around. There's no guarantee that the DLL actually matches the source. This hasn't been a bigger issue for OHM since the projects under External rarely change, but...

The reason this came up is that Aga.Controls needs to be updated. It uses hard coded values designed for standard 96 DPI displays. Because of that, the OHM GUI has display issues on high DPI displays that need to be fixed.

In order to fix Aga.Controls for OHM, I can make a new commit that changes both the source code and modifies Aga.Controls.dll. I'll know it's fine since I made it, but no one else should need to trust a DLL that I make since I'm not a trusted maintainer.

It will be better for everyone OHM users if they don't need to trust DLLs that come from random contributors, and it will be better for OHM maintainers since they won't need to ensure that the committed DLL still matches the source.

Does that sound reasonable?

**Comment by bigpodgurc** [comment]
Personaly im still more for dll way but just like u im not maintaier im just very enthusiastic about it

**Comment by dwilhelm** [comment]
That's fair. Maybe you're using it in a different way than me. Are there benefits to using the DLLs?

**Comment by Phyxion** [comment]
I'm fully for doing it this way, but is there anything changed to the components in question? If they are 1:1 from source it's better to migrate them to NuGet.

**Comment by dwilhelm** [comment]
TreeViewAdv (Aga.Controls in the repo) is already tweaked for OHM from the original upstream. I'm not sure about oxyplot.

**Comment by Phyxion** [comment]
OK, just checked OxyPlot, they are PCL and thus not compatible anymore with .NET 2.0 here. We'd need to update to .NET 4.0 (or possibly .NET 4.5 as they seem to remove support for .NET 4.0).
TreeViewAdv is indeed change (auto expand for example), so I'll merge the PR. Thanks :)

**Pull request merged**
