### PR TITLE
Add preliminary support for Nuvoton NCT6799D

### PR DESCRIPTION
**Pull request by Alexx999**
Partially addresses #843 
On X670E Hero it allows controlling fans (my primary goal) but the temps seem wrong so this is definitely not 100% complete just yet.

### CODE REVIEW

**Comment by Rem0o** [comment]
Search arround Github a bit, found this file:
https://github.com/NetBSD/src/blob/8320b6cc18fa066411b30896566869b05eb29ed7/sys/dev/ic/nslm7x.c

seems to contains most register addresses you need.

**Comment by jstar81** [comment]
Good to see progress about this, I am about to move from current AMD AM4 platform to new AM5 with Hero X670E board, (just waiting PSU to arrive), and FanControl is a _must,_, I have been using it since I found it, also donated to the project :)

**Comment by Rem0o** [comment]
@jstar81  consider donating to people contributing to this repo too, like @PhyxionNL and @Alexx999, the backend work is not to be neglected.

**Comment by jstar81** [comment]
@Rem0o thanks for your reply, I donated $10 to @PhyxionNL :) Alex is missing Sponsor option for some reason

**Comment by Kodoz** [comment]
Thank you! Built libs for FanControl and now it works with my X670 mobo

**Comment by jstar81** [comment]
> Thank you! Built libs for FanControl and now it works with my X670 mobo

Are you able to help noobies like me, how to build libs?
I would really like to start using FanControl & LibreHardwareMonitor with my new X670E setup :( But so far doesn't recognize any fans except my GPU. Asus own software isn't good.

**Comment by Kodoz** [comment]
> > Thank you! Built libs for FanControl and now it works with my X670 mobo
> 
> Are you able to help noobies like me, how to build libs? I would really like to start using FanControl & LibreHardwareMonitor with my new X670E setup :( But so far doesn't recognize any fans except my GPU. Asus own software isn't good.
e-mail me please

**Comment by PhyxionNL** [comment]
You can also get the binaries here (you must be signed into GitHub):
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/actions/runs/3261148596

**Comment by PhyxionNL** [comment]
@Alexx999 Do you want to do anything still with this PR?

**Comment by Alexx999** [comment]
@PhyxionNL I tried looking into weird temp readings, but without any info/datasheets it's non-trivial, to say the least. Also, CPUID hwmon has exactly the same readings :)
So I'd say it should be merged as-is as there's no readily available info to fix it anyway.

**Comment by PhyxionNL** [comment]
> @PhyxionNL I tried looking into weird temp readings, but without any info/datasheets it's non-trivial, to say the least. Also, CPUID hwmon has exactly the same readings :) So I'd say it should be merged as-is as there's no readily available info to fix it anyway.

Yeah, too bad these datasheets are always missing, so this sounds good, thanks!

**Comment by chunkeey** [comment]
Uh, Question. I've stumbled on this while looking for linux-upstream support of my ASRock X670E PG Lighting (I know different vendor). In my case, the SuperIO identifies itself with the same <code>0xd802</code> ID, but mine has the label "NCT6796D-S" on it.

**Pull request merged**
