### PR TITLE
Bugfix: Crash when access to nvml api is unavailable

### PR DESCRIPTION
**Pull request by sebastian-dev**
Bugfix: Application/Lib Crash when a access to Nividia ML Lib fails.

### CODE REVIEW

**Comment by PhyxionNL** [comment]
This doesn't seem like the right way, IsAvailable should already be set to false when any of these delegates fail.

**Comment by sebastian-dev** [comment]
It crashes (sometimes) when you have a valid handle and everything ist ok, 

`
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at LibreHardwareMonitor.Interop.NvidiaML.NvmlDeviceGetPowerUsage(NvmlDevice)
   at LibreHardwareMonitor.Hardware.Gpu.NvidiaGpu.Update()
`

**Comment by PhyxionNL** [comment]
> It crashes (sometimes) when you have a valid handle and everything ist ok,
> 
> `Description: The process was terminated due to an unhandled exception. Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt. Stack: at LibreHardwareMonitor.Interop.NvidiaML.NvmlDeviceGetPowerUsage(NvmlDevice) at LibreHardwareMonitor.Hardware.Gpu.NvidiaGpu.Update()`
> 
> maybe this is a driver issue from NVIDA, but LHM crash. The Delegate dosent fail, it is correct initialized. On the second try after the exception evything works.

That's pretty weird, it sounds like initializing somehow fails. Looking at this doc: https://docs.nvidia.com/deploy/nvml-api/group__nvmlInitializationAndCleanup.html
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/LibreHardwareMonitorLib/Interop/NvidiaML.cs#L199 we now use nvmlInit_v2, but perhaps we should change it to also use nvmlInit as it will fail when any detected GPU is in a bad or unstable state, which sounds like that's preferable.

**Comment by sebastian-dev** [comment]
`it sounds like initializing somehow fails.`
I think it is an issue with the driver. This is only a workarround for the faulty behavior from the nvidia driver interface.

**Pull request merged**
