### PR TITLE
Add support for DIMMs temperature sensor

### PR DESCRIPTION
**Pull request by lich426**
issue (#395)
reference ([https://github.com/CalcProgrammer1/OpenRGB](https://github.com/CalcProgrammer1/OpenRGB))

### CODE REVIEW

**Comment by PhyxionNL** [comment]
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/395#issuecomment-802646198

**Comment by Cubox** [comment]
Hi,

What are the plans regarding this PR?
I think and would like for it to be merged in, as it would bring very coveted sensors.

**Comment by PhyxionNL** [comment]
The problem I've mentioned in the comment still exists, I'd like to get that resolved before merging this in.

**Comment by PhyxionNL** [comment]
@lich426 I think we need to find a solution on how to detect this properly. It should be possible as HWiNFO doesn't detect it either. I've already searched a bit online for this but couldn't really find any documentation on this.

**Pull request closed without merging**
