### PR TITLE
Build on appveyor

### PR DESCRIPTION
**Pull request by DDRBoxman**
Appveyor will create windows builds and save the artifacts.

### CODE REVIEW

**Comment by Phyxion** [comment]
Thank you for the PR!
Any reason why you chose the debug build over the release build?

**Comment by DDRBoxman** [comment]
Nope, just went with whatever the default was.

**Comment by bigpodgurc** [comment]
Arent travis and appveyor compleatly the same thing or am i confusing something (never used any of them im personaly more teamcity)

**Comment by DDRBoxman** [comment]
Travis only has OSX and Linux hosts. Appveyor has Windows hosts.

**Comment by Phyxion** [comment]
Yes, I'll see if I can migrate it to appveyor.

**Comment by LibreHardwareMonitor** [comment]
OK, added, artifacts are available now by clicking the appveyor button. Thank you for the PR.

**Pull request merged**
