### PR TITLE
Added a basic HTML Dashboard

### PR DESCRIPTION
**Pull request by KyodaiKen**
I added the possibility to serve a dashboard using /dashboard request to the webserver. It lacks customization in the LHM UI, but it really works nicely **_once you entered your sensors taken from /data.json_**. It also serves the HTML and Chart.js file. They have to be put in the same directory like the LHM executable for now.

I am new to Github and just started using it. If I do anything weird or wrong please feel free to point it out and tell me how to correct it and do it better.

firefox_2019-04-28_03-04-35

### Future plans
Since LHM already has a plotter feature, I want to export the plotter settings as a JSON the HTML can request. This will make it much easier for the user to set it up in contrast to analyzing the /data.json object to find the sensors they want to see on the dasboard. With that, the dashboard is automatically built up from that data. I might have to add a new dialog box where the user can redirect sensors to certain charts they can create and manage. This is not to replace the plot function, it's rather meant as an addition to that feature. Not everyone likes web technology. But since it is highly customizable by changing the code in the HTML file, I guess this is a nice thing to have for a hardware monitor!

What do you guys think?

### CODE REVIEW

**Comment by MichaelBelgium** [comment]
The plot LHM already has is not really good, this would be a great alternative.

**Comment by KyodaiKen** [comment]
Due to intense heatwaves in my country and also personal stuff I didn't have time to make it more customizable and more dynamic yet. Any help is appreciated!

**Comment by KyodaiKen** [comment]
I may continue work on this soon, will just need to pull the latest changes and manually merge mine into it. I keep y'all updated!

**Comment by KyodaiKen** [comment]
I will close this pull request because I am a GIT n00b and did everything wrong. I will reopen it as soon as I have finished work on the new improved version of the dashboard.

Thanks and best regards,
Kyo

**Pull request closed without merging**
