### PR TITLE
Added support for NCT6687D

### PR DESCRIPTION
**Pull request by lich426**
I have a MSI Z490 UNIFY
the super io chip on this board is NCT6687D
most msi z490 boards use this chip

[LibreHardwareMonitor.Report.txt](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/5009977/LibreHardwareMonitor.Report.txt)

### CODE REVIEW

**Comment by Phyxion** [comment]
Nice work, would it be possible to merge this into the existing Nct677X class? Quite a lot seems broadly the same. Even though Nct677X doesn't catch the name anymore (it didn't already as also other versions are included).

**Comment by lich426** [comment]
I merged it with Nct677X class.
but, there seems to be a problem with the file encoding.

**Comment by Phyxion** [comment]
> I merged it with Nct677X class.
> but, there seems to be a problem with the file encoding.

I think you'll need to save it as UTF8, or you can try to restore the ö in the file manually. The rest seems the same encoding wise.

**Comment by lich426** [comment]
I modified the file :)

**Comment by likeafox** [comment]
Hello, I am trying to understand your code here. You have `Sleep` after each device write like for example in SetControl():
```
WriteByte(_fanControlManualModeRegister, mode);
WriteByte(_fanControlRequestRegister, _fanControlRequestStartCommand);

// need sleep
Thread.Sleep(100);
```
Why is the Sleep necessary, and how did you learn that the Sleep is necessary?

Also can you tell me how you found the addresses of the registers? I am trying to find documentation. Thank you.

**Pull request merged**
