### PR TITLE
Add Noise Sensors support

### PR DESCRIPTION
**Pull request by severgun**
Added sensors type: Noise
Added icon

### CODE REVIEW

**Comment by PhyxionNL** [comment]
Thanks! Please remove the GridV3 from this PR. 
What is the source for the icon? It should be have a permissable license.

**Comment by severgun** [comment]
Replaced icon https://www.iconfinder.com/icons/35383/settings_sound_speaker_icon

**Comment by PhyxionNL** [comment]
> Replaced icon https://www.iconfinder.com/icons/35383/settings_sound_speaker_icon

It's very hard to see, is there another? Or maybe with a little less padding? 😊

**Comment by severgun** [comment]
16x16 hard to see by default.
What about this? https://commons.wikimedia.org/wiki/File:Sound-icon.svg

**Comment by PhyxionNL** [comment]
I agree, but most icons are still somewhat visible 🙂 Yeah, that icon looks good.

**Comment by severgun** [comment]
LibreHardwareMonitor_elG45PBpY2

**Comment by PhyxionNL** [comment]
Thanks @severgun, looks good now, merged.

**Pull request merged**
