### PR TITLE
Fix 'PInvokeStackImbalance' in NVAPI.cs

### PR DESCRIPTION
**Pull request by MmAaXx500**
My problem: [Here](https://stackoverflow.com/questions/54962553/how-to-use-libre-hardware-monitor-library-to-read-gpu-sensors) with my question and my answer :innocent:  
Other people with the same problem: [Here](https://stackoverflow.com/questions/39202455/calling-unmanaged-code-from-c-sharp/39203588)

### CODE REVIEW

**Comment by Phyxion** [comment]
Anyone with NVIDIA that can check this?

**Comment by KyodaiKen** [comment]
I have an RTX 2080ti but I never had any problem with the NVidia sensors. What exactly are the symptoms of PInvokeStackImbalance?

**Comment by MmAaXx500** [comment]
[Here](https://stackoverflow.com/q/54962553/9355850) you can see what I did. The problem only occurs when I use LHM dll from my own application. The LHM worked fine before and after the fix.

**Comment by Phyxion** [comment]
OK sounds good, thanks, merging.

**Pull request merged**
