### PR TITLE
Add CI build number to project version when PR is merged

### LINKED ISSUE #336: LibreHardwareMonitorLib NuGet does not get published correctly
I noticed that on each ci build the version is set to `0.8.5`, this causes `rohith/publish-nuget` to not publish the new nuget because there is a [existing version check](https://github.com/brandedoutcast/publish-nuget/blob/c12b8546b67672ee38ac87bea491ac94a587f7cc/index.js#L108).

The version should be updated to include the ci build number, so for example `0.8.5-ci39`. I guess it should also be marked as prerelease. Ideally the dll would also include the ci version as the file version but that might be harder to do and unnecessary.

### PR DESCRIPTION
**Pull request by MoshiMoshi0**
Updates the `Directory.Build.props` version with a ci build number when a PR is merged, this will publish a new version of LibreHardwareMonitorLib to nuget that will be marked as prerelease. Don't know if this is a "proper" solution so feel free to close this, I dont really want to touch github actions again.

Also cleaned up artifact upload for net452, netstandard20 and nupkg.
Fixes #336.

As a side note I think github actions are terrible, they try to combine code in yaml with so many random restrictions that it becomes a chore to do anything (for example `env` context can be used in `steps.if` but not in `jobs.if`). I dont think I will ever use them, just using nuke build with plain C# code is way way better. `</rant>`

### CODE REVIEW

**Comment by PhyxionNL** [comment]
Thanks, can you rebase this @MoshiMoshi0 and add .NET 5.0?

**Comment by MoshiMoshi0** [comment]
Done

**Comment by PhyxionNL** [comment]
Thanks, how does this work with pre (and "normal") releases now?

**Comment by MoshiMoshi0** [comment]
Everything works as before, but just on the pr merged event the version is updated in `Directory.Build.props` to include the ci build number so the nuget can be pushed. If the version includes a dash '-', it is treated as prerelease on nuget, this ofc does not push a github release marked as prerelease.
One "issue" I found is that on PR merge there will be two ci builds, one for pr merge event and one for the merge commit push event.

Its not be ideal solution I think, but I did not want to change the whole versioning because I dont know if you want to and kept it simple.

A better solution might be to:
* Use GitVersion for versioning, and updating Assembly/File/Informational versions of each ci build.
* Maybe use a separate workflow that only runs on PR merge event that only pushes the nuget and a new github release marked as prerelease, without attaching the artifacts.

**Comment by PhyxionNL** [comment]
Alright, so a version bump for a "normal" release must under this scheme always be done directly on master? I'm not sure whether that's always the ideal condition. What about just writing the bumping the version in the Directory.Build.props file like this:
- New release, change to say `<Version>0.8.7</Version>`. This is now put out as a release.
- Make another commit, and change it to <Version>0.8.8-pre</Version>. If the -pre tag exists in `Version`, append the git id.

If the second commit is done with [ci skip] it would not run a second time.

**Comment by MoshiMoshi0** [comment]
It only needs to be on master now because thats how the workflow is setup, it only runs on master branch. I dont see anything that forces it to be on master. I dont think there was any other branch than master in this repo anyways.

But yea if you ignore this PR you could manually version normal releases and a prereleases, and it will push the nuget just fine. Just think its tedious to bump release version to `0.8.7` and then bump to `0.8.7-pre`.

With this PR releases would work like this:
* Starting version: `0.8.6`
* New merged PR, sets version to `0.8.6-ci39`, pushes a new nuget
* New merged PR, sets version to `0.8.6-ci45`, pushes a new nuget
* New merged PR, sets version to `0.8.6-ci49`, pushes a new nuget
* There was enough changes to warrant a new release so commit a version bump to `0.8.7`, pushes a new nuget, manually post a new github release
* New merged PR, sets version to `0.8.7-ci55`, pushes a new nuget
...

There are many ways you can version so maybe its better if you set it up how you want, I just think we should have a new nuget and optionally github prerelease with each PR since they frequently add support for new hardware. This can be done either by manually bumping versions, or somehow automating it. It does not really matter, its just how much work it will require.

**Comment by PhyxionNL** [comment]
Most of this PR could still be used , I'm just not sold on the idea that pre-releases of the same version number would come after a normal release. A manual version bump is fine, you'd have to do that anyway, otherwise you're never bumping anything.

**Comment by MoshiMoshi0** [comment]
Ah, yes I see what you mean. That will indeed look weird. I guess the solution is to also increase patch part of the version when the pr is merged. So starting with version `0.8.6` each pr will read the version and bump it to `0.8.7` and also add the build number: `0.8.7-ci42`.
 
I guess you also dont have any way to know if the next release will be `0.8.7` or `0.9.0` if you do it manually or auto version in ci.
So there might be a bunch of `0.8.7` prereleases but then the next release will be `0.9.0`. Don't know how to solve that.

**Comment by PhyxionNL** [comment]
> 
> 
> Ah, yes I see what you mean. That will indeed look weird. I guess the solution is to also increase patch part of the version when the pr is merged. So starting with version `0.8.6`, on each pr the ci will read the version and bump it to `0.8.7` and also add the build number: `0.8.7-ci42`.
> 
> I guess you also dont have any way to know if the next release will be `0.8.7` or `0.9.0` if you do it manually or auto version in ci.
> So there might be a bunch of `0.8.7` prereleases but then the next release will be `0.9.0`. Don't know how to solve that.

Yeah, that would work, not sure if that's possible though? If so, that'd be a good idea. Otherwise, it's not much effort to make two commits and start a new version. This script could still largely be used.

**Comment by MoshiMoshi0** [comment]
You can run powershell scripts so anything should be possible.
Pushed a change and now it also increases the patch part of the version. The code looks kinda janky in yaml, at some point it might be better to just use nuke build or cake and call it from github actions.

**Comment by PhyxionNL** [comment]
Any chance it's possible to bump like this (rather than only on PR):
- If Directory.Build.props is changed, leave it as-is.
- Otherwise, +0.0.1 to version + git?

**Comment by MoshiMoshi0** [comment]
You want to bump the version and post the git release on each pushed commit?

**Comment by PhyxionNL** [comment]
To master branch only. Sometimes pull requests aren't used and that would cause no version bump then.


________________________________

**Comment by PhyxionNL** [comment]
To master branch only. Sometimes pull requests aren't used and that would cause no version bump then.

**Comment by MoshiMoshi0** [comment]
Sorry for the delay, pushed the changes. 
Checking if the actual version part in the build props file was changed might be difficult, so we only check for the file change.

**Pull request merged**
