### PR TITLE
CPU Refactoring

### PR DESCRIPTION
**Pull request by Xcalibur37**

### CODE REVIEW

**Comment by Xcalibur37** [comment]
- Refactored Generic CPU, Intel, and AMD
- Intel: Added P-Core, E-Core descriptors for applicable micro architectures
- Intel: Fixed thread designations for multi-threaded processors.
- AMD17: Broke out classes and dependencies.

**Comment by PhyxionNL** [comment]
Thanks, but this is far too large, can you please split this up in separate PRs?

**Comment by Xcalibur37** [comment]
The issue with the size is because of the GenericCPU refactor. I had to make changes to the super classes to properly implement. Can we leave it this time and I will break it down to smaller chunks for future updates?

**Comment by PhyxionNL** [comment]
This is far too large to review like this, looking a bit through the code it should be possible to split most bits up.

**Comment by Xcalibur37** [comment]
Sorry about that. Let me look into this and see what I can do. I probably should have submitted a PR as soon as I did the GenericCPU refactor and left the AMD and Intel improvements until after. I will see if I can rebuild that. Sorry for the inconvenience.

**Comment by Tellinq** [comment]
Also, this did contain data changes from out of scope commits from #1474 - I typically would avoid mass revert commits - from my experience those just end up being messy. Instead what I would have done is made your branch from the base master branch from this repository instead of your fork, and then rebuilt the changes again accordingly.

Just my 2¢ on how I would recommend going about this when reattempting this

**Pull request closed without merging**
