### PR TITLE
Fixing-ITE-IT8628E to show up to 6 fans instead of 4

### PR DESCRIPTION
**Pull request by sp991**
This is an attempt to fixe issue #849

### CODE REVIEW

**Comment by Rem0o** [comment]
Does the 5th address register that gets used actually maps properly to the 5th fan channel?

**Comment by sp991** [comment]
> Does the 5th address register that gets used actually maps properly to the 5th fan channel?

I have no idea. All this is pretty new to me and I was just playing arround yesterday. I'm pretty knowledgeable in tech but I have no development background and doesn't know any code language except some basic VBA after fiddling in excel macro. I'm an accountant by training. 

I guess I would need to compile from my fork in order to test but I have no idea how to do this and I ended up here after installing Fan Control which is a little utility that uses LHM in the background.

**Comment by Rem0o** [comment]
@sp991 I know, I'm FanControl developper.

Well yes you would need to compile and test your changes. You can't just throw code at the wall and hope for it to stick.

**Comment by sp991** [comment]
@Rem0o thanks for looking into this, I though pull request were there so that others can test and validate that the changes are working. I would not be throwing code at the wall having no idea how to come up with said code. But I found a fan count right next to my motherboard ID so I figured that changing that count to 5 would solve the issue. Obviously someone with more knowledge will have to look into this.

Thanks

**Comment by sp991** [comment]
> Does the 5th address register that gets used actually maps properly to the 5th fan channel?

Hello,

I did some reading and installed MS Visual Studio and build LHM from my branch. I can now see the 5th Fan with a RPM reading but the control seems to be missing. I'll read through  [IT87XX.cs](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/850/commits/e0d34e9030d4dd954b013c6b509e69277c6c2000) to see if I can find what else needs a modification.
image

**Comment by sp991** [comment]
After playing around in MS Visual Studio far too long, I found out that the control field in LHM only shows something when Fan Control is controlling them or maybe another 3rd party application but if they are managed by BIOS or motherboard software, the field is blank instead of showing the actual % of load.
So  the 2 line of code I changed are working perfectly and I put the LHM library in the Fan Control folder and managed to control the Fan#5
image

**Comment by PhyxionNL** [comment]
I checked it87 driver and they state that this is a custom design that supports up to 6, so please change 5 to 6 for both and I'll merge :)

**Comment by sp991** [comment]
It's done, thank you so much!

**Pull request merged**
