### PR TITLE
[Core] netstandard support, drop PInvokeDelegateFactory and replace w…

### PR DESCRIPTION
**Pull request by LORDofDOOM**
…ith direct dll calls in ADL.cs, NVAPI.cs, FTD2XX.cs, create project and solution file for netstandard, add compiler option in KernelDriver.cs and Ring0.cs - These options are not required for library mode. 

netstandard is not default (dont referenced in OpenHardwareMonitor.sln), anything works as in previous versions (.NET2.0) - netstandard library is optional only - We can merge this later but need to drop legacy .NET2.0 support...

### CODE REVIEW

**Comment by Phyxion** [comment]
Another review.

- The readme change should be undone.
- I would like this added as one project/sln with multi-targeting. For example, base it on the standard project and change the <TargetFramework ...> in the csproj to <TargetFramework**s**>net452;netstandard2.0</TargetFrameworks> and update the references. Then we have just one thing to maintain. Then we'll also update to .NET 4.5.2, which I feel will be fine for all.

**Comment by LORDofDOOM** [comment]
I can undo the readme change - Add it just to show that compile is working :-)

I'll change it to multitarget - Thats IMHO the better option but it will break compatibility to old VS versions... Is that OK ?

I'll start working now - Think the update will be done tomorrow :-)

**Comment by Phyxion** [comment]
Yes, that's no problem, it works with VS2017 community edition, which is free for everyone. Most open source projects that want to support .NET Standard have made this change, so I think we'll be OK.

**Comment by LORDofDOOM** [comment]
I've done the upgrade :-)

Clean merge should be possible - I've also upgrade sln files because a build in other version than VS2017 is not possible

**Comment by Phyxion** [comment]
Could you also update the readme? The registry nuget package also doesn't resolve. Is there any reason you included a preview release instead of the latest stable (4.4.0)?
But then I can merge it, as the rest looks good to me  👍

I also noticed you created a NuGet package, ideally this should be merged into this, and then just a 
> OpenHardwareMonitorLib
 which contains both net452 and core dlls.

**Comment by LORDofDOOM** [comment]
Hi,

yes we currently need the preview packages because System.Management is not in main nuget repo... I'll change this after the final release from Microsoft. I've add the needed nuget repo in appveyor in my master branch.

I create a nuget package because I need to build on other systems and don't want to clone repo each time :-)

Should I also include appveyor in merge request ?

**Comment by Phyxion** [comment]
If your appveyor config works and uses the correct project, sure.

About the nuget package, I think we should be able to include all the required builds here and make one package that contains both net452 and core. There's plenty of projects with such a nuget package at least. Is there a way to semi automate building and uploading to nuget? If not, then a manual upload shouldn't be too hard.
On Jan 2, 2018, at 17:59, LORDofDOOM <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

yes we currently need the preview packages because System.Management is not in main nuget repo... I'll change this after the final release from Microsoft. I've add the needed nuget repo in appveyor in my master branch.

I create a nuget package because I need to build on other systems and don't want to clone repo each time :-)

Should I also include appveyor in merge request ?

**Pull request merged**
