### PR TITLE
Imported OpenHardwareMonitorReport.

### PR DESCRIPTION
**Pull request by rafaelrmrr**
Hi. With this pull request, I imported OpenHardwareMonitorReport (pull request #1000) to LibreHardwareMonitor, renaming it to LibreHardwareMonitorReport. It is maintained in a separated project.

Also, testing the LibreHardwareMonitorReport I have expected some problem with a PhysicalDisk in use by Oracle Virtualbox. I solved it ignoring the storage when WindowsStorage.GetStorageInfo return null.

Att,
Rafael Rosa

### CODE REVIEW

**Comment by nobodysu** [comment]
Looked forward for the Report part. :(

**Comment by Phyxion** [comment]
I think it would be more useful to add this to the main application (for example as a command line argument) rather than another executable.

**Comment by nobodysu** [comment]
I agree, but there might be no one who implements it. (I don't have the expertise unfortunately)

**Comment by rafaelrmrr** [comment]
I did this and maintened as another executable, first because its how was first developed in OpenHardwareMonitor, and also, it dont include GUI libraries, so its a smaller executable to install in many servers, permiting be called within an ssh or other tool and after closes giving a result and permiting me write a script for continuosly (5 minutes pooling) monitor the server temperature.

**Comment by rafaelrmrr** [comment]
But, actualy, there is and other pull-request in OpenHardwareMonitor, doing more things than this. I hope test and adapt the Open Hardware Monitor pull request #1115.

**Comment by totalnooob** [comment]
Hello im getting error SystemAccessViolationException every couple of run of the exe what i do with it?

**Comment by rafaelrmrr** [comment]
@totalnooob are you running my fork? This pull request wasn't merged with LibreHardwareMonitor.

**Comment by totalnooob** [comment]
Yes your fork ive downloaded the zip file with binary

**Comment by rafaelrmrr** [comment]
I got this error, when I tryed run the program from Ondrive or Google Drive (don't remenber). It create a LibreHardwareMonitorLib.sys file, but can't load the driver from one of these drives. Can you try run the files from other folders? And also, can you send a print screen of error, including the files on the folder, during the error?
Att,Rafael Rosa
    Em quarta-feira, 12 de fevereiro de 2020 12:06:20 BRT, totalnooob <notifications@github.com> escreveu:  
 
 
Yes your fork ive downloaded the zip file with binary

**Comment by totalnooob** [comment]
`Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr ptr, Object structure, Boolean allowValueClasses)
   at System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr ptr, Type structureType)
   at System.Runtime.InteropServices.Marshal.PtrToStructure[T](IntPtr ptr)
   at LibreHardwareMonitor.Hardware.Storage.NVMeSamsung.IdentifyController(SafeHandle hDevice, NVME_IDENTIFY_CONTROLLER_DATA& data)
   at LibreHardwareMonitor.Hardware.Storage.NVMeSmart.GetInfo()
   at LibreHardwareMonitor.Hardware.Storage.NVMeGeneric.GetDeviceInfo(StorageInfo storageInfo)
   at LibreHardwareMonitor.Hardware.Storage.NVMeGeneric.CreateInstance(StorageInfo storageInfo, ISettings settings)
   at LibreHardwareMonitor.Hardware.Storage.AbstractStorage.CreateInstance(String deviceId, UInt32 driveNumber, UInt64 diskSize, Int32 scsiPort, ISettings settings)
   at LibreHardwareMonitor.Hardware.Storage.StorageGroup..ctor(ISettings settings)
   at LibreHardwareMonitor.Hardware.Computer.Open()
   at LibreHardwareMonitorReport.Program.Main(String[] args)
`
[](https://imgur.com/a/Mg8dIC0)

**Comment by totalnooob** [comment]
What do you think? Can you resolve the issue?

**Comment by rafaelrmrr** [comment]
A storage problem. Some disk may be locked. If you have visual studio, you may try compile a new executable, disabling disk monitoring, changing the line computer.IsStorageEnabled = true to computer.IsStorageEnabled = false.
Can you try? If you can't I can do this, but only tomorrow. May be? If this works, it confirm that os a storage problem, helping isolate the problem.
Let's solve the problem. I think will be good merge may fork with actual LibreHardwareMonitor. This may a solved bug.
Att,Rafael Rodrigo Moreira Rosa

Enviado do Yahoo Mail no Android 
 
  <div>Em qui, 20 20e fev 20e 2020 às 9:59, totalnooob</div><div><notifications@github.com> escreveu:</div>   
What do you think? Can you resolve the issue?

**Comment by totalnooob** [comment]
I dont have the visual studio installed if you try it tomorrow would be fine. i only need to monitor cpu temperature

**Comment by rafaelrmrr** [comment]
Hi,
Let's see if this suports a zip file. Try using this. It won't check disk sensors status.
Att,
    Em quinta-feira, 20 de fevereiro de 2020 12:36:33 BRT, totalnooob <notifications@github.com> escreveu:  
 
 
I dont have the visual studio installed if you try it tomorrow would be fine. i only need to monitor cpu temperature

**Comment by rafaelrmrr** [comment]
Ooops,
Please, forget the other. Try this.
Att
    Em sexta-feira, 21 de fevereiro de 2020 14:37:40 BRT, Rafael Rodrigo Moreira Rosa <rafaelrmrr@yahoo.com.br> escreveu:  
 
  Hi,
Let's see if this suports a zip file. Try using this. It won't check disk sensors status.
Att,
    Em quinta-feira, 20 de fevereiro de 2020 12:36:33 BRT, totalnooob <notifications@github.com> escreveu:  
 
 
I dont have the visual studio installed if you try it tomorrow would be fine. i only need to monitor cpu temperature

**Comment by rafaelrmrr** [comment]
Hi, @totalnooob.

The file attached by mail wasn't sent to this thread. So, please download using this google drive link:
https://drive.google.com/file/d/1PnSBkU2b5iJE219EOmGHoLhoVCaDCiad/view?usp=sharing
or Github:
[Debug.zip](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/4241247/Debug.zip)

Please inform the result. I hope it will solve your problem.

Thanks
Rafael Rosa

**Comment by totalnooob** [comment]
Thanks a lot it works fine 👍 
Have a nice day

**Comment by totalnooob** [comment]
> Hi, @totalnooob.
> 
> The file attached by mail wasn't sent to this thread. So, please download using this google drive link: https://drive.google.com/file/d/1PnSBkU2b5iJE219EOmGHoLhoVCaDCiad/view?usp=sharing or Github: [Debug.zip](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/files/4241247/Debug.zip)
> 
> Please inform the result. I hope it will solve your problem.
> 
> Thanks Rafael Rosa

Hi can you compile it for the latest version?

**Pull request closed without merging**
