### PR TITLE
Aquacomputer mps

### PR DESCRIPTION
**Pull request by fboldog**
This PR add a basic support for Aquacomputer's MPS (USB High Flow) sensor.
The code based on https://github.com/aquacomputer/plugin_sdk/blob/master/DeviceSdk/mps/data_layout_mps.h and some direct data dumps. :)

aquacomputer-mps

### CODE REVIEW

**Comment by fboldog** [comment]
aquacomputer-mps

**Comment by Phyxion** [comment]
Can you rebase this and #131 on master @fboldog?

**Comment by fboldog** [comment]
Ofc. :)

**Comment by fboldog** [comment]
@Phyxion done. :)

**Comment by fboldog** [comment]
Please **don't** merge, there is a small bug in actual external sensor reading. :(

**Comment by fboldog** [comment]
@Phyxion done. :)

**Comment by Phyxion** [comment]
Can you format MPS according to editorconfig? For example, { belong on new line.

**Comment by fboldog** [comment]
Yup. After 7pm CET.

**Pull request merged**
