### PR TITLE
Support NVME drives

### LINKED ISSUE #16: Support for M2 SSD
Adding support for M2 SSD? 
Noticed this since I got a NVME 960 EVO and its only getting noticed as a GenericHarddisk

### PR DESCRIPTION
**Pull request by damieng**
This is a port of https://github.com/openhardwaremonitor/openhardwaremonitor/pull/984 from OpenHardwareMonitor to LibreHardwareMonitor.

The code currently has issues however (not caused by the port, all present in upstream PR):

## Issue summary

- Most people will see their NVME drives disappear entirely from LibreHardwareMonitor.
- If they do appear and you have more than one they might have each others details.
- Hitting Reset in the monitor makes those NVME that did appear disappear.

### Why don't drives appear at all?

1. PR uses the `Identify 0x06` command via `NVMePassThroughSrbIoCode 0xe0002000` for NVME drives.
2. Some manufacturer-supplied Windows drivers *DO* support this (tested Samsung & HP).
3. The default `Microsoft NVM Express Controller` Windows driver *does not* support this.
4. Manufacturers drivers must be manually installed for this to work (even Windows Update won't help).

This explains why in that PR thread some people were seeing it and some weren't.

## Multi-drive details potential mangling

- An inner loop tries to perform a DeviceIoCtl call for `\\.\Scsi` starting at 0 increasing up to 31
- There is no code to make sure that the physical drive and the "Scsi" drive are actually the same device 

## Reset causes device disappearance

The counter in the inner loop for matching up with the "Scsi" devices is never reset back to 0.

## Next Steps

1. Ensure right physical drive gets paired with right NVME - will solve mangling and reset.
2. Ensure fallback from NVME mode to something generic so it's no worse than current behavior.
3. Investigate using `STORAGE_QUERY_PROPERTY` from https://docs.microsoft.com/en-us/windows/win32/fileio/working-with-nvme-devices to see if any more luck than PR author.

Would fix #16 and #56

### CODE REVIEW

**Comment by aquacomputer** [comment]
Hi, we have currently an implementation with a full NVMe support, 
this: https://github.com/openhardwaremonitor/openhardwaremonitor/pull/984 version is not working good and all samsung nvme drives are detected.

**Comment by Phyxion** [comment]
I don't have a NVME drive to test this, so any other feedback is appreciated. If @aquacomputer has another implementation for this (not entirely sure what you mean with your above comment) then perhaps something can be combined here.

**Comment by aquacomputer** [comment]
all issues from this base implementation are fixed here:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/107
and some other new sensors (activity, read/write rates)

**Comment by damieng** [comment]
Closing in favor of https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/107

**Pull request closed without merging**
