### PR TITLE
Add functionality for choosing log dir.

### PR DESCRIPTION
**Pull request by MysterX83**
This branch add the functionality to choose the logging directory.

### CODE REVIEW

**Comment by Phyxion** [comment]
Can you undo the code style changes in designer file? It's almost impossible to compare like this.

**Comment by MysterX83** [comment]
It's generate code, is there a style guide file (i.e from resharper) that i can load?

**Comment by Phyxion** [comment]
There isn't at the moment, I'd like a ReSharper refactor at some point but have not done so because it makes it harder to merge changes against OHM base.

**Comment by Phyxion** [comment]
Closing due to stale, feel free to reopen in future.

**Pull request closed without merging**
