### PR TITLE
Add support for .NET 7

### PR DESCRIPTION
**Pull request by pomianowski**
PR adds support for .NET 7 in **LibreHardwareMonitorLib**. Additionally, it extends published artifacts and readme.

### CODE REVIEW

**Comment by PhyxionNL** [comment]
This doesn't build on CI.

**Comment by pomianowski** [comment]
> This doesn't build on CI.

It looks like we have to wait again for Microsoft to update its machines for GitHub.

**Comment by pomianowski** [comment]
Related https://github.com/actions/runner-images/issues/6531

**Comment by pomianowski** [comment]
Hey @PhyxionNL, newest workers should use the Visual Studio 17.4

**Pull request merged**
