### PR TITLE
Add support for ASUS ROG CROSSHAIR X670E GENE 

### PR DESCRIPTION
**Pull request by Crosenhain**
Adding basic support for the ASUS ROG CROSSHAIR X670E GENE, so LibreHardwareMonitorLib can read the `T SENSOR`

### CODE REVIEW

**Comment by threeohclock** [comment]
I believe this pull broke the library for this motherboard.  When I use FanControl I am now getting this:

> 6/16/2023 8:50:38 AM: LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.EmbeddedController+MultipleBoardRecordsFoundException: Multiple board records refer to the same model 'ROG_CROSSHAIR_X670E_EXTREME'
   at LibreHardwareMonitor.Hardware.Motherboard.Lpc.EC.EmbeddedController.Create(Model model, ISettings settings) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Lpc\EC\EmbeddedController.cs:line 337
   at LibreHardwareMonitor.Hardware.Motherboard.Motherboard..ctor(SMBios smBios, ISettings settings) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\Motherboard.cs:line 71
   at LibreHardwareMonitor.Hardware.Motherboard.MotherboardGroup..ctor(SMBios smbios, ISettings settings) in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Motherboard\MotherboardGroup.cs:line 18
   at LibreHardwareMonitor.Hardware.Computer.AddGroups() in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Computer.cs:line 501
   at LibreHardwareMonitor.Hardware.Computer.Open() in C:\Users\Remi\source\repos\FanControl\LibreHardwareMonitor\LibreHardwareMonitorLib\Hardware\Computer.cs:line 495
   at FanControl.Domain.BackendProviders.LHM.LHMBackendProvider.Open()

**Comment by PhyxionNL** [comment]
You're right @threeohclock, fixed:
https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/7e841d70f10da566bc02fb97b650eea2b682012f

**Comment by Crosenhain** [comment]
Apologies, thanks for the fix

**Comment by threeohclock** [comment]
Thank you so much!  Really appreciate the immediate fix.

**Pull request merged**
