### PR TITLE
Add Processor Cache to SMBios

### PR DESCRIPTION
**Pull request by Pomianowski**
CPU Cache information based on SMBIOS documentation

### CODE REVIEW

**Comment by PhyxionNL** [comment]
Thanks, can you format the code according to the code styles?

**Comment by Pomianowski** [comment]
> Thanks, can you format the code according to the code styles?
@PhyxionNL 

Hey,
You mean [this](https://google.github.io/styleguide/csharp-style.html) for example?
I'm still learning, so if that's not a problem for you, I'd be grateful if you said what I'm doing wrong.

**Comment by PhyxionNL** [comment]
No, you need to format the document. Press Ctrl+K + Ctrl+D (default key combination, otherwise you can find it in the Edit menu I think). If you use VS2019 it should automatically apply the style based on this editor config file: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/.editorconfig.

**Comment by Pomianowski** [comment]
> No, you need to format the document. Press Ctrl+K + Ctrl+D (default key combination, otherwise you can find it in the Edit menu I think). If you use VS2019 it should automatically apply the style based on this editor config file: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/master/.editorconfig.

Ok, thank you.
I think it's done

**Comment by PhyxionNL** [comment]
All good now, thanks for the PR @Pomianowski!

**Pull request merged**
