### PR TITLE
Add Network (NIC) support

### PR DESCRIPTION
**Pull request by LORDofDOOM**
All credits to XiaofengdiZhu (https://github.com/XiaofengdiZhu/openhardwaremonitor/commits/EditeByXiaofengdizhu)

I think that function is pretty useful - Everything works in my test :-)

### CODE REVIEW

**Comment by Phyxion** [comment]
Does this show the network adapter name as well? I agree that this is useful, but I do have some things that I don't like as-is. For example, I'm not sure if naming the sensortype 'InternetSpeed' is the correct name for it. I'm more inclined to name it something like 'Bandwidth', or 'Throughput'. 

I also think that the sensor names aren't as descriptive as they can be. Take this for example: Total Data Downloaded in Static. What does that do? A name like Network Utilization isn't perfect either, it's already a Load sensor, so it'd be Network Utilization Load. Compare this to other HW, such as NVIDIA, it's just Memory (of SensorType.Load) too. The same applies to all the Speed names.

**Comment by LORDofDOOM** [comment]
Yes it show adapter name (I've 4 NIC in my PC incl. VMWare Adapters). 

I Agree with naming - Internet Speed is not correct naming. Bandwidth is more logical and we should use this as name.

The "Load" Sensor is IMHO correct - It show the Utilization of the NIC (e.g. 100Mbps if 10% for a 1000Mbps adapter)

"Total Data Downloaded in Static" is also a bit confusing... It should show Data Upload/Download since first start of OHM and preserve this data after a reboot.

**Comment by Phyxion** [comment]
Yeah, but CPU/GPU Core Load/Utilization isn't named as such either, it's just CPU/GPU Core, I think the same logic applies to Network. I'll also have to see this how it looks in the software, will also check this this weekend. 

I think that Throughput is probably the best name for it to describe (looking at how MS has it in Windows at least).

The "in Static", given that it only works when OHM is running, it would just be confusing. I think that sensor can just be dropped.

**Comment by Phyxion** [comment]
Alright, had some time to review this. It seems to work well, but I have some feedback before I'm going to merge this.

- I don't think loopback/tunnel devices need to be added (such as Teredo Tunneling and Loopback Pseudo). 
- It would be nice that - instead of showing 'Ethernet' for the main connecting, it would show the adapter name as well, such as Realtek RTLxxxx - Ethernet. 
- Naming as said above. Network Utilization can just be Network, this is clear enough I think.

**Comment by LORDofDOOM** [comment]
I've created a new branch (I already working with the netstandard merge)

- Changed name from InternetSpeed to Throughput
- Use Windows values for total transfered data (Static is now useful)
- Drop non physical devices like loopback

Here is the new branch - Please check :-)

[https://github.com/LORDofDOOM/LibreHardwareMonitor/commits/netstandard2_nic](https://github.com/LORDofDOOM/LibreHardwareMonitor/commits/netstandard2_nic)

**Comment by Phyxion** [comment]
I think you should check if the nic != Loopback instead, and use the enumeration instead of the string. The names/descriptions also need to be changed. The rest look good. Maybe the appveyor image can now be changed to vs17 although I can modify that myself too.
On Nov 23, 2017, at 02:00, LORDofDOOM <notifications@github.com<mailto:notifications@github.com>> wrote:

I've created a new branch (I already working with the netstandard merge)

  *   Changed name from InternetSpeed to Throughput
  *   Use Windows values for total transfered data (Static is now useful)
  *   Drop non physical devices like loopback

Here is the new branch - Please check :-)

https://github.com/LORDofDOOM/LibreHardwareMonitor/commits/netstandard2_nic

**Comment by Phyxion** [comment]
Just replying here, how did you setup nuget? Is it possible to publish a new nuget package semi automatically? I'm currently building a nupkg already (based on your code).

**Comment by LORDofDOOM** [comment]
Hi,

I create nuget directly in Build (https://github.com/LORDofDOOM/LibreHardwareMonitor/blob/master/OpenHardwareMonitorLib.csproj) 

I've uploaded the nuget package manually - But automatic upload is possible with e.g. batch file in csproj after build

**Comment by zstoichev** [comment]
Hello, any estimate on the merge?

**Comment by LORDofDOOM** [comment]
Here is my new (up-to-date) PR:

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/52

Closing this :-)

**Pull request closed without merging**
