### PR TITLE
Added support for ASUS MAXIMUS Z790 DARK HERO

### PR DESCRIPTION
**Pull request by diablo1281**
I added model and identification for ASUS MAXIMUS Z790 DARK HERO

Added for NCT6798D:
- voltages
- temperatures
- fans and controls

Added for ASUS EC:
- VRM temp
- CPU_OPT fan
- checked T_Sensor, Water_IN/OUT
- `Water Flow` not validated (lack of hardware to check it)

All check done with help of HWINFO64.
Before:
image

After changes (UPDATED with second commit):
image

### CODE REVIEW

**Comment by Tellinq** [comment]
Hey, I figured I’d might pitch in since I also have a friend with a STRIX Z790-A. Seems like the data entry is rather similar to this

image

https://github.com/Tellinq/LibreHardwareMonitor/commit/bf983cd268e99e4166ae73312bd860f39a1921ce

My branch did get some stuff wrong, and EC support was never really tested.

- For temperature index 22, mind trying to see if that actually gets the CPU core temperature? I tried index 21 first as well, nothing showed up. Might be a similar story for you.
- Looks like temperature index 13 is actually the PCH temperature like what I found with Z790-A. Index 12 might not be necessary
- The Integrated Memory Controller (voltage index 11, I incorrectly named DRAM since this is DDR5, not DDR4) is normally supposed to be 1:1, although from what I gathered, this might not be the case. Mind seeing if that is the same with you when checking HWiNFO?
- Check voltage indexes 13 and 14 and see if those are also the CPU System Agent and CPU Input Auxiliary respectively

If what you get is similar to the results I got for the Z790-A I may append to add this board once this is merged. I’ll check to see if VRM temps also get detected like yours.

**Comment by diablo1281** [comment]
Thanks @Tellinq for pointing this VRM temp. It is a mistake, as I can't figure out what it points to and forgot to comment it out.

- Index 22 points to `CPU` temperature, according to HWINFO. Indexes 14-21 and 9-11 don't report anything. Indexes 3-8 report some garbage.
- Index 13 points to `PCH` temperature, at some point index 12 reported temperature also but now I see it's not necessary.
- Voltage index 13 points to `IVR_VCCSA` and 14 to `VCCIN_AUX` (thanks for tip to check settings 1:1) - what name should I use for them?

Thanks for all the comments, I will update my code.

**Comment by Tellinq** [comment]
VCCSA -> CPU System Agent
VCCIN_AUX -> CPU Input Auxiliary

Temperature indexes 3-8 by the way are typically PSU auxiliary sensors are typically have no use. I typically just don’t include them (nor even bother to put them in the comments)

I’m curious about voltage index 11 and to see how that shows up compared to HWiNFO results. What happens if you set that to be 1:1? If that doesn’t align with HWiNFO/your actual RAM voltage what happens if you use the resistance values I did in my commit.

**Comment by diablo1281** [comment]
Index 10 doesn't align with anything. With default values it show 0.632V, with 1:1 1.264V and with yours 1.249V.
Also values in your commit seems a bit strange compared to other ASUS boards.

image

**Comment by Tellinq** [comment]
Yeah the values I used for IMC VDD is a bit weird. However the results I got ended up aligning with the actual RAM voltage… so I’m not sure what the discrepancy is.

This is primarily the reason (aside from the incomplete ASUS EC) why I never PR’d this data entry since I wasn’t sure why I was getting the resistance values as is… but it’s at least what I could do to make it align with *something*. I imagine that the rest of ASUS DDR5 board entries people did here had something similar and decided to just skip altogether.

**Comment by diablo1281** [comment]
Any chance for approval and merge? I would love to not have to custom build lib for FanControl :)

**Pull request merged**
