### PR TITLE
Fix System.ArgumentException: Invalid identifier on Linux (#1434)

### PR DESCRIPTION
**Pull request by DaVarga**
Fix for #1434

This solution is inspired by the nzxt hardware identifier. https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/5476ac16c9e3c4f1e2692515edb86c55a613cefa/LibreHardwareMonitorLib/Hardware/Controller/Nzxt/KrakenV2.cs#L28

### CODE REVIEW

**Comment by Rem0o** [comment]
Hi,

It seems like this changes doesn't play well with the Razer Fan controller on Windows:
https://github.com/Rem0o/FanControl.Releases/issues/2721#issuecomment-2338384310

The GetSerialNumber() call throws an exception.

I don't know the specifics, but maybe this is a case of "If Linux/Else", or does this original "Invalid Identifier" really affected the Razer device?

**Comment by PhyxionNL** [comment]
I'll revert this @Rem0o.

**Comment by DaVarga** [comment]
@PhyxionNL You should reopen #1434 then.

**Comment by PhyxionNL** [comment]
I've address it differently :)

**Pull request merged**
